---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:15.0.6
  amd64: ghcr.io/hassio-addons/base/amd64:15.0.6
  armv7: ghcr.io/hassio-addons/base/armv7:15.0.6
codenotary:
  base_image: codenotary@frenck.dev
  signer: dev@brenner.tech
