---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:17.2.2
  amd64: ghcr.io/hassio-addons/base/amd64:17.2.2
  armv7: ghcr.io/hassio-addons/base/armv7:17.2.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: dev@brenner.tech
