---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:16.2.1
  amd64: ghcr.io/hassio-addons/base/amd64:16.2.1
  armv7: ghcr.io/hassio-addons/base/armv7:16.2.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: dev@brenner.tech
