---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:14.3.3
  amd64: ghcr.io/hassio-addons/base/amd64:14.3.3
  armhf: ghcr.io/hassio-addons/base/armhf:14.3.3
  armv7: ghcr.io/hassio-addons/base/armv7:14.3.3
  i386: ghcr.io/hassio-addons/base/i386:14.3.3
codenotary:
  base_image: codenotary@frenck.dev
  signer: dev@brenner.tech
