---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:13.2.2
  amd64: ghcr.io/hassio-addons/base/amd64:13.2.2
  armhf: ghcr.io/hassio-addons/base/armhf:13.2.2
  armv7: ghcr.io/hassio-addons/base/armv7:13.2.2
  i386: ghcr.io/hassio-addons/base/i386:13.2.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: dev@brenner.tech
