---
name: Cloudflared
version: "2026.8.3-pt1"
breaking_versions:
  - 5.3.7
  - 6.0.0
slug: cloudflared_pt_test
description: "PT translation of 
  Use a Cloudflare Tunnel to remotely
  connect to Home Assistant without opening any ports"
#url: "https://github.com/homeassistant-apps/app-cloudflared"
url: "https://github.com/PauloGoncalves86/app-cloudflared"
startup: services
init: false
hassio_api: true
arch:
  - aarch64
  - amd64
map:
  - type: app_config
    read_only: false
  - type: homeassistant_config
    read_only: true
options:
  external_hostname: ""
  additional_hosts: []
ports:
  36500/tcp: null
schema:
  external_hostname: str?
  additional_hosts:
    - hostname: str
      service: str
      disableChunkedEncoding: bool?
  tunnel_name: str?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  tunnel_token: str?
  post_quantum: bool?
  run_parameters:
    - match(^(--edge-bind-address|--edge-ip-version|--grace-period|--ha-connections|--logfile|--loglevel|--pidfile|--protocol|--region|--retries|--tag)=.*$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
